import { describe, expect, it } from "vitest";

import {
  ExportValidationError,
  exportDocument,
  exportValidatedDocument,
} from "../../src/app/export-document";
import { createEmptyEditorDocument } from "../../src/domain/document";
import { asPdfPoint } from "../../src/domain/primitives";
import { unsafeBrand } from "../../src/shared/brand";
import type { EditorDocument } from "../../src/domain/document";
import type { EditorError } from "../../src/domain/errors";
import type { ExportSnapshot, GeneratedPdf } from "../../src/ports/pdf";

describe("exportDocument", () => {
  it("creates an export snapshot and passes it to the exporter port", async () => {
    let receivedSnapshot: ExportSnapshot | undefined;
    const generated: GeneratedPdf = {
      bytes: new Uint8Array([1, 2, 3]),
      sha256: "test_hash",
    };
    const document = createEmptyEditorDocument({
      id: unsafeBrand("document_export_test"),
      createdAt: "2026-08-11T00:00:00.000Z",
    });

    const result = await exportDocument(
      {
        exporter: {
          async export(snapshot) {
            receivedSnapshot = snapshot;
            return generated;
          },
        },
      },
      document,
    );

    expect(result).toBe(generated);
    expect(receivedSnapshot).toMatchObject({
      documentId: document.id,
      revision: document.revision,
      sources: [],
      pages: [],
      objectsByPage: {},
    });
  });

  it("validates generated bytes before returning a downloadable PDF", async () => {
    const generated: GeneratedPdf = {
      bytes: new Uint8Array([1, 2, 3]),
      sha256: "test_hash",
    };
    const document = createEmptyEditorDocument({
      id: unsafeBrand("document_validated_export_test"),
      createdAt: "2026-08-11T00:00:00.000Z",
    });

    const result = await exportValidatedDocument(
      {
        exporter: {
          async export() {
            return generated;
          },
        },
        validator: {
          async validate(request) {
            expect(request).toMatchObject({
              documentId: document.id,
              revision: document.revision,
              generatedBytes: generated.bytes,
            });
            return { ok: true };
          },
        },
      },
      document,
    );

    expect(result).toBe(generated);
  });

  it("validates the final exported structure with intrinsic source page rotation", async () => {
    const generated: GeneratedPdf = {
      bytes: new Uint8Array([1, 2, 3]),
      sha256: "test_hash",
    };
    const sourceId = unsafeBrand<string, "SourceId">(
      "source_intrinsic_rotation",
    );
    const pageId = unsafeBrand<string, "PageId">("page_intrinsic_rotation");
    const document: EditorDocument = {
      ...createEmptyEditorDocument({
        id: unsafeBrand("document_intrinsic_rotation_export_test"),
        createdAt: "2026-08-11T00:00:00.000Z",
      }),
      sources: {
        [sourceId]: {
          id: sourceId,
          fingerprint: "test_fingerprint",
          originalName: "rotated.pdf",
          byteLength: 123,
          pageCount: 1,
          encryption: "none",
          signatureState: "none",
          capabilities: {
            canRender: true,
            canExportOverlay: true,
            canFillSupportedForms: false,
            unsupportedReasons: [],
          },
        },
      },
      pages: [
        {
          id: pageId,
          sourceId,
          sourcePageIndex: 0,
          userRotation: 0,
          geometry: {
            mediaBox: {
              xMin: asPdfPoint(0),
              yMin: asPdfPoint(0),
              xMax: asPdfPoint(612),
              yMax: asPdfPoint(792),
            },
            cropBox: {
              xMin: asPdfPoint(0),
              yMin: asPdfPoint(0),
              xMax: asPdfPoint(612),
              yMax: asPdfPoint(792),
            },
            intrinsicRotation: 90,
          },
        },
      ],
    };

    await exportValidatedDocument(
      {
        exporter: {
          async export() {
            return generated;
          },
        },
        validator: {
          async validate(request) {
            expect(request.expectedPages).toEqual([
              {
                sourcePageIndex: 0,
                width: 792,
                height: 612,
                rotation: 90,
              },
            ]);
            return { ok: true };
          },
        },
      },
      document,
    );
  });

  it("blocks generated bytes that fail validation", async () => {
    const generated: GeneratedPdf = {
      bytes: new Uint8Array([1, 2, 3]),
      sha256: "test_hash",
    };
    const error: EditorError = {
      code: "EXPORT_VALIDATION_FAILED",
      retryable: false,
      messageKey: "export.validation.failed",
      correlationId: "export_validation_test",
      safeMetadata: {
        byteLength: generated.bytes.byteLength,
        revision: 0,
      },
    };
    const document = createEmptyEditorDocument({
      id: unsafeBrand("document_invalid_export_test"),
      createdAt: "2026-08-11T00:00:00.000Z",
    });

    await expect(
      exportValidatedDocument(
        {
          exporter: {
            async export() {
              return generated;
            },
          },
          validator: {
            async validate() {
              return { ok: false, error };
            },
          },
        },
        document,
      ),
    ).rejects.toMatchObject({
      name: "ExportValidationError",
      editorError: error,
    } satisfies Partial<ExportValidationError>);
  });
});
